import React, { useEffect } from 'react';

// Import the images for each artboard
// Adjust these paths to match your project structure
import artboard1Image from '../assets/ByIsland-Artboard_1.png';
import artboard2Image from '../assets/ByIsland-Artboard_2.png';
import artboard3Image from '../assets/ByIsland-Artboard_3.png';

/**
 * ByIslandChart Component
 * 
 * A responsive visualization showing median age by sex with
 * three different layouts for various screen sizes.
 */
const ByIsland = () => {
  useEffect(() => {
    // Handle the ai2html resize function if it exists
    if (window.ResizeAi2html && typeof window.ResizeAi2html === 'function') {
      window.ResizeAi2html();
      
      // Add resize listener
      window.addEventListener('resize', window.ResizeAi2html);
      
      // Cleanup on unmount
      return () => {
        window.removeEventListener('resize', window.ResizeAi2html);
      };
    }
  }, []);

  // This is the ai2html output with image sources replaced
  const htmlContent = `
<!-- Generated by ai2html v0.117.6 - 2025-02-26 16:34 -->
<!-- ai file: ByIsland.ai -->
<style media="screen,print">
	#g-ByIsland-box ,
	#g-ByIsland-box .g-artboard {
		margin:0 auto;
	}
	#g-ByIsland-box p {
		margin:0;
	}
	#g-ByIsland-box .g-aiAbs {
		position:absolute;
	}
	#g-ByIsland-box .g-aiImg {
		position:absolute;
		top:0;
		display:block;
		width:100% !important;
	}
	#g-ByIsland-box .g-aiSymbol {
		position: absolute;
		box-sizing: border-box;
	}
	#g-ByIsland-box .g-aiPointText p { white-space: nowrap; }
	#g-ByIsland-Artboard_1 {
		position:relative;
		overflow:hidden;
	}
	#g-ByIsland-Artboard_1 p {
		font-weight:400;
		line-height:17px;
		height:auto;
		opacity:1;
		letter-spacing:0em;
		font-size:14px;
		text-align:left;
		color:rgb(33,37,41);
		text-transform:none;
		padding-bottom:0;
		padding-top:0;
		mix-blend-mode:normal;
		font-style:normal;
		position:static;
	}
	#g-ByIsland-Artboard_1 .g-pstyle0 {
		font-weight:300;
		text-align:right;
		color:rgb(0,0,0);
	}
	#g-ByIsland-Artboard_1 .g-pstyle1 {
		font-weight:700;
		height:17px;
	}
	#g-ByIsland-Artboard_1 .g-pstyle2 {
		height:17px;
	}
	#g-ByIsland-Artboard_2 {
		position:relative;
		overflow:hidden;
	}
	#g-ByIsland-Artboard_2 p {
		font-weight:400;
		line-height:17px;
		height:auto;
		opacity:1;
		letter-spacing:0em;
		font-size:14px;
		text-align:left;
		color:rgb(33,37,41);
		text-transform:none;
		padding-bottom:0;
		padding-top:0;
		mix-blend-mode:normal;
		font-style:normal;
		position:static;
	}
	#g-ByIsland-Artboard_2 .g-pstyle0 {
		font-weight:300;
		text-align:right;
		color:rgb(0,0,0);
	}
	#g-ByIsland-Artboard_2 .g-pstyle1 {
		font-weight:700;
		height:17px;
	}
	#g-ByIsland-Artboard_2 .g-pstyle2 {
		height:17px;
	}
	#g-ByIsland-Artboard_3 {
		position:relative;
		overflow:hidden;
	}
	#g-ByIsland-Artboard_3 p {
		font-weight:400;
		line-height:17px;
		height:auto;
		opacity:1;
		letter-spacing:0em;
		font-size:14px;
		text-align:left;
		color:rgb(33,37,41);
		text-transform:none;
		padding-bottom:0;
		padding-top:0;
		mix-blend-mode:normal;
		font-style:normal;
		position:static;
	}
	#g-ByIsland-Artboard_3 .g-pstyle0 {
		font-weight:300;
		text-align:right;
		color:rgb(0,0,0);
	}
	#g-ByIsland-Artboard_3 .g-pstyle1 {
		font-weight:700;
		height:17px;
	}
	#g-ByIsland-Artboard_3 .g-pstyle2 {
		height:17px;
	}

	  /* Add media queries to control which artboard shows at different screen sizes */
    @media (min-width: 800px) {
      #g-ByIsland-Artboard_2, #g-ByIsland-Artboard_3 {
        display: none;
      }
    }
    
    @media (min-width: 560px) and (max-width: 799px) {
      #g-ByIsland-Artboard_1, #g-ByIsland-Artboard_3 {
        display: none;
      }
    }
    
    @media (max-width: 559px) {
      #g-ByIsland-Artboard_1, #g-ByIsland-Artboard_2 {
        display: none;
      }
    }
  </style>


</style>

<div id="g-ByIsland-box" class="ai2html">

	<!-- Artboard: Artboard_1 -->
	<div id="g-ByIsland-Artboard_1" class="g-artboard" style="width:800px; height:158.886487117428px;" data-aspect-ratio="5.035" data-min-width="800">
<div style=""></div>
		<img id="g-ByIsland-Artboard_1-img" class="g-ByIsland-Artboard_1-img g-aiImg" alt="" src="${artboard1Image}"/>
		<div id="g-ai0-1" class="g-Layer_1 g-aiAbs" style="top:3.1469%;right:0.4577%;width:8.75%;">
			<p class="g-pstyle0">Median: 55</p>
		</div>
		<div id="g-ai0-2" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:27.9352%;margin-top:-9.4px;left:11.4141%;width:111px;">
			<p class="g-pstyle1">57.5 years old</p>
		</div>
		<div id="g-ai0-3" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:27.9352%;margin-top:-9.4px;left:0.125%;width:71px;">
			<p class="g-pstyle2">Visayas</p>
		</div>
		<div id="g-ai0-4" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:47.446%;margin-top:-9.4px;left:11.4141%;width:50px;">
			<p class="g-pstyle1">55.5</p>
		</div>
		<div id="g-ai0-5" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:47.446%;margin-top:-9.4px;left:0.125%;width:104px;">
			<p class="g-pstyle2">Metro Manila</p>
		</div>
		<div id="g-ai0-6" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:66.9568%;margin-top:-9.4px;left:11.4141%;width:38px;">
			<p class="g-pstyle1">55</p>
		</div>
		<div id="g-ai0-7" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:66.9568%;margin-top:-9.4px;left:0.125%;width:59px;">
			<p class="g-pstyle2">Luzon</p>
		</div>
		<div id="g-ai0-8" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:86.4676%;margin-top:-9.4px;left:11.4141%;width:38px;">
			<p class="g-pstyle1">52</p>
		</div>
		<div id="g-ai0-9" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:86.4676%;margin-top:-9.4px;left:0.125%;width:84px;">
			<p class="g-pstyle2">Mindanao</p>
		</div>
	</div>

	<!-- Artboard: Artboard_2 -->
	<div id="g-ByIsland-Artboard_2" class="g-artboard" style="width:560px; height:160.374767166744px;" data-aspect-ratio="3.492" data-min-width="560" data-max-width="799">
<div style=""></div>
		<img id="g-ByIsland-Artboard_2-img" class="g-ByIsland-Artboard_2-img g-aiImg" alt="" src="${artboard2Image}"/>
		<div id="g-ai1-1" class="g-Layer_2 g-aiAbs" style="top:2.4942%;right:0.2689%;width:12.5%;">
			<p class="g-pstyle0">Median: 55</p>
		</div>
		<div id="g-ai1-2" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:27.676%;margin-top:-9.4px;left:16.2091%;width:111px;">
			<p class="g-pstyle1">57.5 years old</p>
		</div>
		<div id="g-ai1-3" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:27.676%;margin-top:-9.4px;left:0.0986%;width:71px;">
			<p class="g-pstyle2">Visayas</p>
		</div>
		<div id="g-ai1-4" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:47.0057%;margin-top:-9.4px;left:16.2091%;width:50px;">
			<p class="g-pstyle1">55.5</p>
		</div>
		<div id="g-ai1-5" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:47.0057%;margin-top:-9.4px;left:0.0986%;width:104px;">
			<p class="g-pstyle2">Metro Manila</p>
		</div>
		<div id="g-ai1-6" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:66.3354%;margin-top:-9.4px;left:16.2091%;width:38px;">
			<p class="g-pstyle1">55</p>
		</div>
		<div id="g-ai1-7" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:66.3354%;margin-top:-9.4px;left:0.0986%;width:59px;">
			<p class="g-pstyle2">Luzon</p>
		</div>
		<div id="g-ai1-8" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:85.6651%;margin-top:-9.4px;left:16.2091%;width:38px;">
			<p class="g-pstyle1">52</p>
		</div>
		<div id="g-ai1-9" class="g-Layer_2 g-aiAbs g-aiPointText" style="top:85.6651%;margin-top:-9.4px;left:0.0986%;width:84px;">
			<p class="g-pstyle2">Mindanao</p>
		</div>
	</div>

	<!-- Artboard: Artboard_3 -->
	<div id="g-ByIsland-Artboard_3" class="g-artboard" style="max-width: 330px;max-height: 148px" data-aspect-ratio="2.234" data-min-width="0" data-max-width="559">
<div style="padding: 0 0 44.7621% 0;"></div>
		<img id="g-ByIsland-Artboard_3-img" class="g-ByIsland-Artboard_3-img g-aiImg" alt="" src="${artboard3Image}"/>
		<div id="g-ai2-1" class="g-Layer_3 g-aiAbs" style="top:1.354%;right:1.4417%;width:21.2121%;">
			<p class="g-pstyle0">Median: 55</p>
		</div>
		<div id="g-ai2-2" class="g-Layer_3 g-aiAbs g-aiPointText" style="top:23.2781%;margin-top:-9.4px;left:27.5781%;width:111px;">
			<p class="g-pstyle1">57.5 years old</p>
		</div>
		<div id="g-ai2-3" class="g-Layer_3 g-aiAbs g-aiPointText" style="top:23.2781%;margin-top:-9.4px;left:0.3054%;width:71px;">
			<p class="g-pstyle2">Visayas</p>
		</div>
		<div id="g-ai2-4" class="g-Layer_3 g-aiAbs g-aiPointText" style="top:44.2645%;margin-top:-9.4px;left:27.5781%;width:50px;">
			<p class="g-pstyle1">55.5</p>
		</div>
		<div id="g-ai2-5" class="g-Layer_3 g-aiAbs g-aiPointText" style="top:44.2645%;margin-top:-9.4px;left:0.3054%;width:104px;">
			<p class="g-pstyle2">Metro Manila</p>
		</div>
		<div id="g-ai2-6" class="g-Layer_3 g-aiAbs g-aiPointText" style="top:65.2508%;margin-top:-9.4px;left:27.5781%;width:38px;">
			<p class="g-pstyle1">55</p>
		</div>
		<div id="g-ai2-7" class="g-Layer_3 g-aiAbs g-aiPointText" style="top:65.2508%;margin-top:-9.4px;left:0.3054%;width:59px;">
			<p class="g-pstyle2">Luzon</p>
		</div>
		<div id="g-ai2-8" class="g-Layer_3 g-aiAbs g-aiPointText" style="top:86.2372%;margin-top:-9.4px;left:27.5781%;width:38px;">
			<p class="g-pstyle1">52</p>
		</div>
		<div id="g-ai2-9" class="g-Layer_3 g-aiAbs g-aiPointText" style="top:86.2372%;margin-top:-9.4px;left:0.3054%;width:84px;">
			<p class="g-pstyle2">Mindanao</p>
		</div>
	</div>

</div>
  `;

  return (
    <div 
      className="byisland-chart-container"
      dangerouslySetInnerHTML={{ __html: htmlContent }}
    />
  );
};

export default ByIsland;