import React, { useEffect } from 'react';

// Import the images for each artboard
// Adjust these paths to match your project structure
import artboard1Image from '../assets/PoliticalDynasty-Artboard_1.png';
import artboard3Image from '../assets/PoliticalDynasty-Artboard_3.png';
import artboard4Image from '../assets/PoliticalDynasty-Artboard_4.png';

/**
 * PoliticalDynasty Component
 * 
 * A responsive visualization showing median age by sex with
 * three different layouts for various screen sizes.
 */
const PoliticalDynasty = () => {
  useEffect(() => {
    // Handle the ai2html resize function if it exists
    if (window.ResizeAi2html && typeof window.ResizeAi2html === 'function') {
      window.ResizeAi2html();
      
      // Add resize listener
      window.addEventListener('resize', window.ResizeAi2html);
      
      // Cleanup on unmount
      return () => {
        window.removeEventListener('resize', window.ResizeAi2html);
      };
    }
  }, []);

  // This is the ai2html output with image sources replaced
  const htmlContent = `


  <!-- Generated by ai2html v0.117.6 - 2025-03-10 09:23 -->
  <!-- ai file: PoliticalDynasty.ai -->
  <style media="screen,print">
      #g-PoliticalDynasty-box ,
      #g-PoliticalDynasty-box .g-artboard {
          margin:0 auto;
      }
      #g-PoliticalDynasty-box p {
          margin:0;
      }
      #g-PoliticalDynasty-box .g-aiAbs {
          position:absolute;
      }
      #g-PoliticalDynasty-box .g-aiImg {
          position:absolute;
          top:0;
          display:block;
          width:100% !important;
      }
      #g-PoliticalDynasty-box .g-aiSymbol {
          position: absolute;
          box-sizing: border-box;
      }
      #g-PoliticalDynasty-box .g-aiPointText p { white-space: nowrap; }
      #g-PoliticalDynasty-Artboard_1 {
          position:relative;
          overflow:hidden;
      }
      #g-PoliticalDynasty-Artboard_1 p {
          font-weight:300;
          line-height:17px;
          height:auto;
          opacity:1;
          letter-spacing:0em;
          font-size:14px;
          text-align:left;
          color:rgb(33,37,41);
          text-transform:none;
          padding-bottom:0;
          padding-top:0;
          mix-blend-mode:normal;
          font-style:normal;
          position:static;
      }
      #g-PoliticalDynasty-Artboard_1 .g-pstyle0 {
          line-height:16px;
          height:16px;
          font-size:13px;
      }
      #g-PoliticalDynasty-Artboard_1 .g-pstyle1 {
          font-weight:400;
          line-height:16px;
          font-size:13px;
          text-align:center;
      }
      #g-PoliticalDynasty-Artboard_1 .g-pstyle2 {
          height:17px;
      }
      #g-PoliticalDynasty-Artboard_3 {
          position:relative;
          overflow:hidden;
      }
      #g-PoliticalDynasty-Artboard_3 p {
          font-weight:300;
          line-height:16px;
          height:auto;
          opacity:1;
          letter-spacing:0em;
          font-size:13px;
          text-align:left;
          color:rgb(33,37,41);
          text-transform:none;
          padding-bottom:0;
          padding-top:0;
          mix-blend-mode:normal;
          font-style:normal;
          position:static;
      }
      #g-PoliticalDynasty-Artboard_3 .g-pstyle0 {
          height:16px;
      }
      #g-PoliticalDynasty-Artboard_3 .g-pstyle1 {
          font-weight:400;
          text-align:center;
      }
      #g-PoliticalDynasty-Artboard_4 {
          position:relative;
          overflow:hidden;
      }
      #g-PoliticalDynasty-Artboard_4 p {
          font-weight:300;
          line-height:16px;
          height:auto;
          opacity:1;
          letter-spacing:0em;
          font-size:13px;
          text-align:left;
          color:rgb(33,37,41);
          text-transform:none;
          padding-bottom:0;
          padding-top:0;
          mix-blend-mode:normal;
          font-style:normal;
          position:static;
      }
      #g-PoliticalDynasty-Artboard_4 .g-pstyle0 {
          height:16px;
      }
      #g-PoliticalDynasty-Artboard_4 .g-pstyle1 {
          font-weight:400;
          text-align:center;
      }

      /* Add media queries to control which artboard shows at different screen sizes */
    @media (min-width: 930px) {
      #g-PoliticalDynasty-Artboard_3, #g-PoliticalDynasty-Artboard_4 {
        display: none;
      }
    }
    
    @media (min-width: 560px) and (max-width: 929px) {
      #g-PoliticalDynasty-Artboard_1, #g-PoliticalDynasty-Artboard_4 {
        display: none;
      }
    }
    
    @media (max-width: 559px) {
      #g-PoliticalDynasty-Artboard_1, #g-PoliticalDynasty-Artboard_3 {
        display: none;
      }
    }
  
  </style>
  
  <div id="g-PoliticalDynasty-box" class="ai2html">
  
      <!-- Artboard: Artboard_1 -->
      <div id="g-PoliticalDynasty-Artboard_1" class="g-artboard" style="width:800px; height:351px;" data-aspect-ratio="2.279" data-min-width="800">
  <div style=""></div>
          <img id="g-PoliticalDynasty-Artboard_1-img" class="g-PoliticalDynasty-Artboard_1-img g-aiImg" alt="" src="${artboard1Image}"/>
          <div id="g-ai0-1" class="g-md g-aiAbs g-aiPointText" style="top:3.3682%;margin-top:-8.8px;left:0.0625%;width:82px;">
              <p class="g-pstyle0">8 bills filed</p>
          </div>
          <div id="g-ai0-2" class="g-md g-aiAbs g-aiPointText" style="top:24.7357%;margin-top:-8.8px;left:0.0625%;width:29px;">
              <p class="g-pstyle0">6</p>
          </div>
          <div id="g-ai0-3" class="g-md g-aiAbs g-aiPointText" style="top:46.1032%;margin-top:-8.8px;left:0.0625%;width:29px;">
              <p class="g-pstyle0">4</p>
          </div>
          <div id="g-ai0-4" class="g-md g-aiAbs g-aiPointText" style="top:67.4707%;margin-top:-8.8px;left:0.0625%;width:29px;">
              <p class="g-pstyle0">2</p>
          </div>
          <div id="g-ai0-5" class="g-md g-aiAbs" style="top:86.6097%;left:16.895%;margin-left:-1.1875%;width:2.375%;">
              <p class="g-pstyle1">0</p>
          </div>
          <div id="g-ai0-6" class="g-md g-aiAbs" style="top:86.6097%;left:29.2154%;margin-left:-1.1875%;width:2.375%;">
              <p class="g-pstyle1">0</p>
          </div>
          <div id="g-ai0-7" class="g-md g-aiAbs" style="top:86.6097%;left:47.7129%;margin-left:-1.1875%;width:2.375%;">
              <p class="g-pstyle1">0</p>
          </div>
          <div id="g-ai0-8" class="g-md g-aiAbs" style="top:86.6097%;left:53.8731%;margin-left:-1.1875%;width:2.375%;">
              <p class="g-pstyle1">0</p>
          </div>
          <div id="g-ai0-9" class="g-md g-aiAbs" style="top:86.6097%;left:66.2019%;margin-left:-1.1875%;width:2.375%;">
              <p class="g-pstyle1">0</p>
          </div>
          <div id="g-ai0-10" class="g-md g-aiAbs" style="top:86.6097%;left:84.691%;margin-left:-1.1875%;width:2.375%;">
              <p class="g-pstyle1">0</p>
          </div>
          <div id="g-ai0-11" class="g-md g-aiAbs" style="top:86.6097%;left:90.8681%;margin-left:-1.1875%;width:2.375%;">
              <p class="g-pstyle1">0</p>
          </div>
          <div id="g-ai0-12" class="g-md g-aiAbs g-aiPointText" style="top:97.2608%;margin-top:-9.4px;left:3.0443%;width:53px;">
              <p class="g-pstyle2">2007</p>
          </div>
          <div id="g-ai0-13" class="g-md g-aiAbs g-aiPointText" style="top:97.2608%;margin-top:-9.4px;left:15.3815%;width:53px;">
              <p class="g-pstyle2">2009</p>
          </div>
          <div id="g-ai0-14" class="g-md g-aiAbs g-aiPointText" style="top:97.2608%;margin-top:-9.4px;left:21.5417%;width:53px;">
              <p class="g-pstyle2">2010</p>
          </div>
          <div id="g-ai0-15" class="g-md g-aiAbs g-aiPointText" style="top:97.2608%;margin-top:-9.4px;left:27.702%;width:53px;">
              <p class="g-pstyle2">2011</p>
          </div>
          <div id="g-ai0-16" class="g-md g-aiAbs g-aiPointText" style="top:97.2608%;margin-top:-9.4px;left:33.8622%;width:53px;">
              <p class="g-pstyle2">2012</p>
          </div>
          <div id="g-ai0-17" class="g-md g-aiAbs g-aiPointText" style="top:97.2608%;margin-top:-9.4px;left:40.0392%;width:53px;">
              <p class="g-pstyle2">2013</p>
          </div>
          <div id="g-ai0-18" class="g-md g-aiAbs g-aiPointText" style="top:97.2608%;margin-top:-9.4px;left:46.1995%;width:53px;">
              <p class="g-pstyle2">2014</p>
          </div>
          <div id="g-ai0-19" class="g-md g-aiAbs g-aiPointText" style="top:97.2608%;margin-top:-9.4px;left:52.3596%;width:53px;">
              <p class="g-pstyle2">2015</p>
          </div>
          <div id="g-ai0-20" class="g-md g-aiAbs g-aiPointText" style="top:97.2608%;margin-top:-9.4px;left:58.5199%;width:53px;">
              <p class="g-pstyle2">2016</p>
          </div>
          <div id="g-ai0-21" class="g-md g-aiAbs g-aiPointText" style="top:97.2608%;margin-top:-9.4px;left:64.6969%;width:53px;">
              <p class="g-pstyle2">2017</p>
          </div>
          <div id="g-ai0-22" class="g-md g-aiAbs g-aiPointText" style="top:97.2608%;margin-top:-9.4px;left:70.8572%;width:53px;">
              <p class="g-pstyle2">2018</p>
          </div>
          <div id="g-ai0-23" class="g-md g-aiAbs g-aiPointText" style="top:97.2608%;margin-top:-9.4px;left:77.0173%;width:53px;">
              <p class="g-pstyle2">2019</p>
          </div>
          <div id="g-ai0-24" class="g-md g-aiAbs g-aiPointText" style="top:97.2608%;margin-top:-9.4px;left:83.1775%;width:53px;">
              <p class="g-pstyle2">2020</p>
          </div>
          <div id="g-ai0-25" class="g-md g-aiAbs g-aiPointText" style="top:97.2608%;margin-top:-9.4px;left:89.3546%;width:53px;">
              <p class="g-pstyle2">2021</p>
          </div>
          <div id="g-ai0-26" class="g-md g-aiAbs g-aiPointText" style="top:97.2608%;margin-top:-9.4px;left:95.5149%;width:53px;">
              <p class="g-pstyle2">2022</p>
          </div>
          <div id="g-ai0-27" class="g-md g-aiAbs g-aiPointText" style="top:97.1004%;margin-top:-8.8px;left:9.2045%;width:51px;">
              <p class="g-pstyle0">2008</p>
          </div>
      </div>
  
      <!-- Artboard: Artboard_3 -->
      <div id="g-PoliticalDynasty-Artboard_3" class="g-artboard" style="width:560px; height:354.309110383343px;" data-aspect-ratio="1.581" data-min-width="560" data-max-width="799">
  <div style=""></div>
          <img id="g-PoliticalDynasty-Artboard_3-img" class="g-PoliticalDynasty-Artboard_3-img g-aiImg" alt="" src="${artboard3Image}"/>
          <div id="g-ai1-1" class="g-sm g-aiAbs g-aiPointText" style="top:3.3367%;margin-top:-8.8px;left:0.0893%;width:82px;">
              <p class="g-pstyle0">8 bills filed</p>
          </div>
          <div id="g-ai1-2" class="g-sm g-aiAbs g-aiPointText" style="top:24.5047%;margin-top:-8.8px;left:0.0893%;width:29px;">
              <p class="g-pstyle0">6</p>
          </div>
          <div id="g-ai1-3" class="g-sm g-aiAbs g-aiPointText" style="top:45.6726%;margin-top:-8.8px;left:0.0893%;width:29px;">
              <p class="g-pstyle0">4</p>
          </div>
          <div id="g-ai1-4" class="g-sm g-aiAbs g-aiPointText" style="top:66.8406%;margin-top:-8.8px;left:0.0893%;width:29px;">
              <p class="g-pstyle0">2</p>
          </div>
          <div id="g-ai1-5" class="g-sm g-aiAbs" style="top:85.5185%;left:17.4936%;margin-left:-1.6964%;width:3.3929%;">
              <p class="g-pstyle1">0</p>
          </div>
          <div id="g-ai1-6" class="g-sm g-aiAbs" style="top:85.5185%;left:29.7199%;margin-left:-1.6964%;width:3.3929%;">
              <p class="g-pstyle1">0</p>
          </div>
          <div id="g-ai1-7" class="g-sm g-aiAbs" style="top:85.5185%;left:48.0762%;margin-left:-1.6964%;width:3.3929%;">
              <p class="g-pstyle1">0</p>
          </div>
          <div id="g-ai1-8" class="g-sm g-aiAbs" style="top:85.5185%;left:54.1894%;margin-left:-1.6964%;width:3.3929%;">
              <p class="g-pstyle1">0</p>
          </div>
          <div id="g-ai1-9" class="g-sm g-aiAbs" style="top:85.5185%;left:66.4325%;margin-left:-1.6964%;width:3.3929%;">
              <p class="g-pstyle1">0</p>
          </div>
          <div id="g-ai1-10" class="g-sm g-aiAbs" style="top:85.5185%;left:84.772%;margin-left:-1.6964%;width:3.3929%;">
              <p class="g-pstyle1">0</p>
          </div>
          <div id="g-ai1-11" class="g-sm g-aiAbs" style="top:85.5185%;left:90.902%;margin-left:-1.6964%;width:3.3929%;">
              <p class="g-pstyle1">0</p>
          </div>
          <div id="g-ai1-12" class="g-sm g-aiAbs g-aiPointText" style="top:96.1935%;margin-top:-8.8px;left:3.0884%;width:51px;">
              <p class="g-pstyle0">2007</p>
          </div>
          <div id="g-ai1-13" class="g-sm g-aiAbs g-aiPointText" style="top:96.1935%;margin-top:-8.8px;left:15.3315%;width:51px;">
              <p class="g-pstyle0">2009</p>
          </div>
          <div id="g-ai1-14" class="g-sm g-aiAbs g-aiPointText" style="top:96.1935%;margin-top:-8.8px;left:27.5579%;width:51px;">
              <p class="g-pstyle0">2011</p>
          </div>
          <div id="g-ai1-15" class="g-sm g-aiAbs g-aiPointText" style="top:96.1935%;margin-top:-8.8px;left:39.801%;width:51px;">
              <p class="g-pstyle0">2013</p>
          </div>
          <div id="g-ai1-16" class="g-sm g-aiAbs g-aiPointText" style="top:96.1935%;margin-top:-8.8px;left:52.0274%;width:51px;">
              <p class="g-pstyle0">2015</p>
          </div>
          <div id="g-ai1-17" class="g-sm g-aiAbs g-aiPointText" style="top:96.1935%;margin-top:-8.8px;left:64.2705%;width:51px;">
              <p class="g-pstyle0">2017</p>
          </div>
          <div id="g-ai1-18" class="g-sm g-aiAbs g-aiPointText" style="top:96.1935%;margin-top:-8.8px;left:76.4968%;width:51px;">
              <p class="g-pstyle0">2019</p>
          </div>
          <div id="g-ai1-19" class="g-sm g-aiAbs g-aiPointText" style="top:96.1935%;margin-top:-8.8px;left:88.7399%;width:51px;">
              <p class="g-pstyle0">2021</p>
          </div>
      </div>
  
      <!-- Artboard: Artboard_4 -->
      <div id="g-PoliticalDynasty-Artboard_4" class="g-artboard" style="max-width: 330px;max-height: 356px" data-aspect-ratio="0.926" data-min-width="0" data-max-width="559">
  <div style="padding: 0 0 107.9768% 0;"></div>
          <img id="g-PoliticalDynasty-Artboard_4-img" class="g-PoliticalDynasty-Artboard_4-img g-aiImg" alt="" src="${artboard4Image}"/>
          <div id="g-ai2-1" class="g-xs g-aiAbs g-aiPointText" style="top:3.5985%;margin-top:-8.8px;left:0.1516%;width:82px;">
              <p class="g-pstyle0">8 bills filed</p>
          </div>
          <div id="g-ai2-2" class="g-xs g-aiAbs g-aiPointText" style="top:24.6468%;margin-top:-8.8px;left:0.1516%;width:29px;">
              <p class="g-pstyle0">6</p>
          </div>
          <div id="g-ai2-3" class="g-xs g-aiAbs g-aiPointText" style="top:45.6951%;margin-top:-8.8px;left:0.1516%;width:29px;">
              <p class="g-pstyle0">4</p>
          </div>
          <div id="g-ai2-4" class="g-xs g-aiAbs g-aiPointText" style="top:66.7434%;margin-top:-8.8px;left:0.1516%;width:29px;">
              <p class="g-pstyle0">2</p>
          </div>
          <div id="g-ai2-5" class="g-xs g-aiAbs" style="top:84.7544%;left:18.8843%;margin-left:-2.8788%;width:5.7576%;">
              <p class="g-pstyle1">0</p>
          </div>
          <div id="g-ai2-6" class="g-xs g-aiAbs" style="top:84.7544%;left:30.8921%;margin-left:-2.8788%;width:5.7576%;">
              <p class="g-pstyle1">0</p>
          </div>
          <div id="g-ai2-7" class="g-xs g-aiAbs" style="top:84.7544%;left:49.2113%;margin-left:-2.8788%;width:5.7576%;">
              <p class="g-pstyle1">0</p>
          </div>
          <div id="g-ai2-8" class="g-xs g-aiAbs" style="top:84.7544%;left:54.9243%;margin-left:-2.8788%;width:5.7576%;">
              <p class="g-pstyle1">0</p>
          </div>
          <div id="g-ai2-9" class="g-xs g-aiAbs" style="top:84.7544%;left:66.9404%;margin-left:-2.8788%;width:5.7576%;">
              <p class="g-pstyle1">0</p>
          </div>
          <div id="g-ai2-10" class="g-xs g-aiAbs" style="top:84.7544%;left:84.9604%;margin-left:-2.8788%;width:5.7576%;">
              <p class="g-pstyle1">0</p>
          </div>
          <div id="g-ai2-11" class="g-xs g-aiAbs" style="top:84.7544%;left:90.9808%;margin-left:-2.8788%;width:5.7576%;">
              <p class="g-pstyle1">0</p>
          </div>
          <div id="g-ai2-12" class="g-xs g-aiAbs g-aiPointText" style="top:95.9303%;margin-top:-8.8px;left:3.1911%;width:51px;">
              <p class="g-pstyle0">2007</p>
          </div>
          <div id="g-ai2-13" class="g-xs g-aiAbs g-aiPointText" style="top:95.9303%;margin-top:-8.8px;left:15.2152%;width:51px;">
              <p class="g-pstyle0">2009</p>
          </div>
          <div id="g-ai2-14" class="g-xs g-aiAbs g-aiPointText" style="top:95.9303%;margin-top:-8.8px;left:27.2231%;width:51px;">
              <p class="g-pstyle0">2011</p>
          </div>
          <div id="g-ai2-15" class="g-xs g-aiAbs g-aiPointText" style="top:95.9303%;margin-top:-8.8px;left:39.2475%;width:51px;">
              <p class="g-pstyle0">2013</p>
          </div>
          <div id="g-ai2-16" class="g-xs g-aiAbs g-aiPointText" style="top:95.9303%;margin-top:-8.8px;left:51.2554%;width:51px;">
              <p class="g-pstyle0">2015</p>
          </div>
          <div id="g-ai2-17" class="g-xs g-aiAbs g-aiPointText" style="top:95.9303%;margin-top:-8.8px;left:63.2796%;width:51px;">
              <p class="g-pstyle0">2017</p>
          </div>
          <div id="g-ai2-18" class="g-xs g-aiAbs g-aiPointText" style="top:95.9303%;margin-top:-8.8px;left:75.2874%;width:51px;">
              <p class="g-pstyle0">2019</p>
          </div>
          <div id="g-ai2-19" class="g-xs g-aiAbs g-aiPointText" style="top:95.9303%;margin-top:-8.8px;left:87.3119%;width:51px;">
              <p class="g-pstyle0">2021</p>
          </div>
      </div>
  
  </div>
  
  <!-- End ai2html - 2025-03-10 09:23 -->
  
  `;

  return (
    <div 
      className="politicaldynasty-chart-container"
      dangerouslySetInnerHTML={{ __html: htmlContent }}
    />
  );
};

export default PoliticalDynasty;